summon-mob:
  active-worlds:
    - "warn"
  max-companion-distance: 10
  max-companion-num: 2
  mob-spawn-period: # tick

  summoner:
    ground-block-ids:
      - "98"
      - "98:1"
      - "98:2"
    lowest-ground-height: 50
    highest-ground-height: 100

    # chance >= 0.01
    mobtype:
      zombie:  # default
        spawn-chance: 50
        min-distance: 7
        max-distance: 40
      skeleton:
        spawn-chance: 50
        min-distance: 7
        max-distance: 40